services:
  postgres:
    container_name: postgres-sql-hims
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hospital-inventory
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  # keycloak:
  #   container_name: keycloak-hims
  #   image: quay.io/keycloak/keycloak:26.0.7
  #   ports:
  #     - 9090:8080
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #   command:
  #     - start-dev
  #     - --import-realm
  #   volumes:
  #     - ./keycloak/realms:/opt/keycloak/data/import
  #   depends_on:
  #     - postgres
  #   networks:
  #     - spring-demo
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local